#!.venv/bin/python3.12
"""
Source: script generated by Claude Sonnet prompted by ebeshero on 6 January 2026.
Startup script for Saxon MCP Server
Handles configuration loading and server initialization
"""

import json
import sys
import logging
from pathlib import Path
from saxon_mcp_server import SaxonXMLMCPServer


def setup_logging(log_dir: str):
    """Configure logging"""
    log_path = Path(log_dir)
    log_path.mkdir(exist_ok=True)

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(log_path / 'server.log'),
            logging.StreamHandler(sys.stdout)
        ]
    )
    return logging.getLogger(__name__)


def load_config(config_path: str = './config.json'):
    """Load server configuration"""
    with open(config_path, 'r') as f:
        return json.load(f)


def main():
    # Load configuration
    config = load_config()

    # Setup logging
    logger = setup_logging(config['log_dir'])
    logger.info("Starting Saxon MCP Server...")

    # Initialize server
    try:
        server = SaxonXMLMCPServer(
            xml_path=config['xml_data_path'],
            schema_path=config.get('xml_schema_path'),
            backup_dir=config['backup_dir']
        )
        logger.info("Server initialized successfully")
        logger.info(f"XML file: {config['xml_data_path']}")
        logger.info(f"Schema: {config.get('xml_schema_path', 'None')}")

        # In a real MCP server, you'd start the server here
        # For now, we'll just keep it ready for MCP SDK integration
        logger.info("Server ready for MCP connections")

    except Exception as e:
        logger.error(f"Failed to start server: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()